marslite_cartesian_motion_controller:
  type: "position_controllers/CartesianMotionController"
  end_effector_link: "robotiq_85_base_link"
  robot_base_link: "tm_base"
  target_frame_topic: "target_frame"
  joints:
  - tm_shoulder_1_joint
  - tm_shoulder_2_joint
  - tm_elbow_joint
  - tm_wrist_1_joint
  - tm_wrist_2_joint
  - tm_wrist_3_joint

  pd_gains:
    trans_x: {p: 5.0}
    trans_y: {p: 5.0}
    trans_z: {p: 5.0}
    rot_x: {p: 2.0}
    rot_y: {p: 2.0}
    rot_z: {p: 2.0}
  solver:
    error_scale: 0.25